In [7]:
import pandas as pd

ticket=pd.read_csv('/home/jimbrootan/Desktop/ML_data/ticket_08_2017.csv') #read the file
ticket.shape
ticket
data=ticket.iloc[:,6:13] #splitted the file using iloc
data_grp= data.groupby(['sync_tkt_route_name','sync_tkt_schedule_no','sync_tkt_trip_no','sync_tkt_start_stage_name',
                       'sync_tkt_end_stage_name'],as_index=False).agg({'sync_tkt_full_count':'sum'}) #groupping ,and aggrigate values as sum of all ticket count

/home/jimbrootan/anaconda3/envs/pythonds/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,sync_tkt_route_name,sync_tkt_schedule_no,sync_tkt_trip_no,sync_tkt_start_stage_name,sync_tkt_end_stage_name,sync_tkt_full_count
0,ANGLVLY-KTYM,1,1,8MILE,MANIMALA,13
1,ANGLVLY-KTYM,1,1,8MILE,PKALAM,3
2,ANGLVLY-KTYM,1,1,ALAMPALLY,KPARA,1
3,ANGLVLY-KTYM,1,1,ALAMPALLY,MANIMALA,1
4,ANGLVLY-KTYM,1,1,CHETTEDA,MANIMALA,3
...,...,...,...,...,...,...
45745,VAIKOM-PNCHKAD,3,5,VAIKOM,PUTANPALOM,1
45746,VAIKOM-PNCHKAD,3,6,KUMARAKOM,KOTTAYAM,1
45747,VAIKOM-PNCHKAD,3,6,VAIKOM,TALAYAZHOM,1
45748,VAIKOM-PNCHKAD,3,7,VAIKOM,KAVANATNKAR,1
45749,VAIKOM-PNCHKAD,3,7,VAIKOM,KOTTAYAM,1

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

X=data_grp.iloc[:,[0,1,2,3,4]].values # splitted in X and y
y=data_grp.iloc[:,[-1]].values # y chosen last colum
# print(y)


encoder=LabelEncoder()
X[:,0]=encoder.fit_transform(X[:,0]) #encoding the data 
X[:,3]=encoder.fit_transform(X[:,3])
X[:,4]=encoder.fit_transform(X[:,4])


X_train,X_test,y_train,y_test=train_test_split(X,y)  #generation of all train and split datas

model=LinearRegression() #linearRegression
 
model.fit(X_train,y_train) #teaching

predictions=model.predict(X_test) #prediction
print('preditions :\n', predictions)

preditions :
 [[4.56487712]
 [6.01718056]
 [5.35775032]
 ...
 [6.52608037]
 [4.87333641]
 [5.2605903 ]]